export type SendTask = {
  name: string;
  email: string;
  startDate: string;
  endDate: string;
  complement: string;
  reference: string;
  address: string;
  phone: string;
  orderNumber: string;
  description: string;
  value: string;
  valueDriver: string;
  type: string;
  key: string;
  driver:string;
  team:string;
  rule:string;
  model:string;
  declaredValue:string;
};
